#ifndef EVENT_H
#define EVENT_H

// CONSTS
#define MAGNITUDE_MIN 1
#define MAGNITUDE_MAX 5
#define TAM_MAX_NOME_REGIAO 64
#define TAM_MIN_NOME_TIPO 32

// tipos de evento
typedef enum {
  // acidente de transito
  ACIDENTE_DE_TRANSITO_SEM_VITIMAS = 0,
  ACIDENTE_DE_TRANSITO_COM_VITIMA_LEVE = 1,
  ACIDENTE_DE_TRANSITO_COM_VITIMA_GRAVE = 2,
  ENGAVETAMENTO_NA_VIA_EXPRESSA = 3,
  ATROPELAMENTO_DE_PEDESTRE = 4,
  VEICULO_EM_CHAMAS_NA_PISTA = 5,
  // infra
  SEMAFORO_INOPERANTE = 6,
  SEMAFORO_INTERMITENTE = 7,
  QUEDA_DE_POSTE_ILUMINAÇÃO = 8,
  BUEIRO_ABERTO = 9,
  // energia
  QUEDA_DE_ENERGIA_BAIRRO_RESIDENCIAL = 10,
  QUEDA_DE_ENERGIA_CENTRO_COMERCIAL = 11,
  QUEDA_DE_ENERGIA_AREA_INDUSTRIAL = 12,
  QUEDA_DE_ENERGIA_EM_HOSPITAL = 66,
  EXPLOSAO_DE_TRANSFORMADOR = 13,
  BLECAUTE_TOTAL = 14,
  // alagamento
  ALAGAMENTO_BAIRRO_RESIDENCIAL = 15,
  ALAGAMENTO_CENTRO_COMERCIAL = 16,
  ALAGAMENTO_ZONA_INDUSTRIAL = 17,
  GALERIA_PLUVIAL_TRANSBORDANDO = 18,
  // incendio
  QUEIMA_DE_LIXO_OU_MATO = 19,
  INCENDIO_FLORESTAL = 20,
  INCENDIO_EM_EDIFICIO_RESIDENCIAL = 21,
  INCENDIO_EM_EDICIO_COMERCIAL = 22,
  INCENDIO_EM_PLANTA_INDUSTRIAL = 23,
  INCENDIO_EM_REGIAO_PERIFERICA = 24,
  INCENDIO_EM_SHOPPING_CENTER = 25,
  INCENDIO_EM_INSTITUICAO_DE_ENSINO = 26,
  INCENDIO_EM_PREDIO_PUBLICO = 27,
  INCENDIO_EM_MASSA = 28,
  // desastres naturais
  VENTANIA = 29,
  VENDAVAL = 30,
  CICLONE = 31,
  TORNADO = 32,
  CHUVA_DE_GRANIZO = 33,
  TEMPESTADE_MEDIA = 34,
  TEMPESTADE_SEVERA = 35,
  TEMPESTADE_CRITICA = 36,
  ONDA_DE_CALOR_EXTREMO = 37,
  ONDA_DE_FRIO_EXTREMO = 38,
  NEVASCA = 39,
  ENCHENTE = 40,
  TERREMOTO = 41,
  // segurança publica
  FURTO = 42,
  ASSALTO_A_TRANSEUNTES = 43,
  ARRASTAO = 44,
  ASSALTO_AO_BANCO = 51,
  SEQUESTRO_DE_TRANSEUNTE = 45,
  SEQUESTRO_DE_ONIBUS = 46,
  SEQUESTRO_DE_AVIAO = 47,
  TIROTEIO_EM_VIA_PUBLICA = 48,
  TIROTEIO_ESCOLAR = 49,
  INVASAO_ARMADA_A_EDIFICIO = 50,
  CONFRONTO_DE_FACCOES = 52,
  BOMBA_EM_VIA_PUBLICA = 53,
  // desatres estruturais
  DESLIZAMENTO_DE_TERRA_EM_COMUNIDADE = 54,
  DESABAMENTO_DE_PREDIO_RESIDENCIAL = 55,
  DESABAMENTO_DE_INSTUICAO_DE_ENSINO = 56,
  DESABAMENTO_DE_PREDIO_COMERCIAL = 57,
  DESABAMENTO_DE_PLANTA_INDUSTRIAL = 58,
  COLAPSO_DE_VIADUTO = 59,
  VAZAMENTO_DE_GAS_EM_AREA_DENSAMENTE_POVOADA = 60,
  VAZAMENTO_QUIMICO_ZONA_INDUSTRIAL = 61,
  EXPLOSAO_DE_POSTO_DE_COMBUSTIVEL = 62,
  ROMPIMENTO_DE_BARRAGEM = 63,
  // saude publica
  SURTO_DE_DOENCA = 64,
  CONTAMINACAO_DE_AGUA_POTAVEL = 65
} TipoEvento;

// status
typedef enum{
  ATIVO = 0,
  RESOLVIDO = 1
} StatusEvento;

typedef struct {
  int dia;
  int mes;
  int ano;
  int hora;
  int minuto;
  int segundo;
} DataHora;

// /\/\/\ EVENTO
typedef struct {
  int id; // primary key
  TipoEvento tipo;
  int magnitude; // severidade
  DataHora timestamp;
  char regiao[TAM_MAX_NOME_REGIAO];
  StatusEvento status;
} Evento;

// /\/\/\ FUNCS UTILITARIAS
const char *tipo_p_string(TipoEvento tipo);
const char *status_p_string(StatusEvento status);
int valida_evento(const Evento *e);
void exibe_evento(const Evento *e);
void datahora_p_string(const DataHora *dh, char *buffer, int tam_buffer);
int valida_datahora(const DataHora *dh);

int magnitude_por_tipo(TipoEvento tipo);

#endif
